### ISSUE TITLE
`pkt_of_buf` should return Error rather than throwing exceptions

### ISSUE THREAD

**Issue by yomimono** [mirage/charrua-core#35]
See https://github.com/yomimono/charrua-client/pull/6 on `charrua-client`, which should be merged into this repository.

**Comment by haesbaert** [comment]
I've pushed 5a25d8f9362872d0f49ad3d66300c24fd8a45451
that should deal with the remaining exceptions, could you please check if I got it right ?

**Comment by yomimono** [comment]
That's a big wrap, don't see any `Invalid_argument`s leaking out of there :) since you've nicely identified the functions that can throw there, we could instead wrap just those, but this works fine too.

**Comment by yomimono** [comment]
Also, thank you for taking care of this!

**Comment by haesbaert** [comment]
No problem !

I opted out for the wrap to make sure we don't miss it in further aditions
and cause this is pretty much the most dangerous function in the code.

**Comment by yomimono** [comment]
haesbaert: I'll tag this as 0.4.1 unless you have some objection?

**Comment by haesbaert** [comment]
Hmm I'd prefer 0.4 only. Since we had 0.3 and not 0.3.0

Im was not using gnu versioning (never saw much value), I could be
convinced though.

**Comment by yomimono** [comment]
unfortunately I already tagged an 0.4, although it's not yet referenced in any opam repository, so I'd like not to move the tag; could do an 0.5 instead though?

**Comment by yomimono** [comment]
(most of the other mirage packages are major.minor.patch and try to do something semver-y, although since most have a major number of 0 it's not really applicable)

**Comment by haesbaert** [comment]
In that case I'd vote for going 1.0.0.

I mean it is not compatible with 0.3 anyway, and 0.4.1 after a 0.3 would be
strange.

What do you think ?

**Comment by yomimono** [comment]
To be honest, as long as `opam` does the right thing I don't really care :) 1.0.0 is fine by me too.

**Comment by yomimono** [comment]
After all of that I seem to have been a confused kid about what I'd tagged - can't find an 0.4 anywhere, so I'll just use that here, since the only reason not to was that I'd already tagged it.

**Comment by haesbaert** [comment]
Ok by me, sorry I missed your previous reply, only noticed now.

v0.4 we go then.

Please make it

**Comment by haesbaert** [comment]
arggh I was writing "Please make it v0.4" then noticed you did it already,
hate typing on the phone.

**Comment by haesbaert** [comment]
Should we merge charrua-client on this release or the next one ?

**Comment by yomimono** [comment]
Next one, unless you have a branch you've been hiding. :)

**Comment by haesbaert** [comment]
gege nono, didn't wanna steal your commits. We can do it marrakech or something.
