### ISSUE TITLE
Take time as an Int32.t in seconds in Dhcp_server.input_pkt.

### ISSUE THREAD

**Issue by haesbaert** [mirage/charrua-core#42]
float made sense in the past since Unix.time and mirage's clock gave it in floats.

Now it makes no sense anymore, we should use Int32.t which would also avoid a bunch of conversions.

**Comment by hannesm** [comment]
is there any absolute time in DHCP on the wire (or only relative times, i.e. the lease period)?  and time is expressed in seconds as a 4 byte unsigned integer I assume?

I'd somehow expect the tick/handler to accept a `Ptime.t` (`int * int64`) -- this is what `PCLOCK.now_d_ps` returns, and based on that decide which leases to expire/renew/...

**Comment by haesbaert** [comment]
The times are always relative, the only drawback I see is that with a monotonic clock it gets harder to reason about when a lease expires (we need to know when "now" is.).

I couldn't figure out what Ptime.t (int * int64)  is
what is the int and what is the int64 ?

The second thing is, I would not be able to use Duration.to_sec in it (in mirage skeleton), since on a 32bit system I'd have only 31 bits to express time.

**Comment by hannesm** [comment]
ptime: look at the source, https://github.com/dbuenzli/ptime/blob/master/src/ptime.ml#L45-L68

I suspect there are two different time things we're talking about here: the lease time to be written on the wire, and the server which needs to find out which leases have expired now.  For the latter, I'd use an explicit time (either periodically as tick, or as part of every input) -- see https://hannes.nqsb.io/Posts/ARP for further explanation what I mean.  ATM I'd suspect that no explicit time function, but rather requiring a Ptime.t in each input call would be more efficient (I've plans to rework ARP to not have an explicit `tick` funciton)..

**Comment by haesbaert** [comment]
Yes, time is always expressed as int32 on dhcp options.

There are some odd DHCP options that use absolute time, they're obsolete and not handled by the library. We still interpret them but the only the user of the library may decide to do something with it.

What you suggest is exactly like things were, if you always pass an absolute timer or a relative timer, the library will work correctly, as long as the absolute timer never goes back (which could be the case before if someone changed the date).

Actually by using monotonic we respect the leases correctly in case the date changes, this was my orinal idea in the past, but I had no access to monotonic clocks in mirage.

**Comment by haesbaert** [comment]
Argh, now I realize I posted this issue before deciding to use a monotonic time as input.

We can't use an int32 as asbolute since it is too short, but a monotonic int32 we can.

**Comment by haesbaert** [comment]
Have a look at: d689ac99ccda6e961b4554d546ebebf12c6e868c
I didn't commit to master.

**Comment by hannesm** [comment]
looks good to me
