### ISSUE TITLE
Jbuilder generates bad .merlin in lib/

### ISSUE THREAD

**Issue by haesbaert** [mirage/charrua-core#62]
Since the topkg port, it seems merlin is broken.

It works for me if I removed the following two lines from lib/.merlin for example:
FLG -ppx "../_build/default/.ppx/ppx_sexp_conv+ppx_cstruct/ppx.exe --as-ppx --cookie 'library-name="dhcp_wire"' -no-check"
FLG -w -40 -w -40

Probably the problem is just the first, I've no idea what that is. I can't really code without merlin, does anyone know what's going on ?

**Comment by haesbaert** [comment]
If I start merlin on another project (which works ok), and then try to open dhcp_server.ml on charrua-core, emacs buffer shows something more useful:

(merlin) backtrace: 
Merlin failed with error: "Error while running external preprocessor
Command line: ../_build/default/.ppx/ppx_sexp_conv+ppx_cstruct/ppx.exe --as-ppx --cookie 'library-name=dhcp_wire' -no-check '/var/folders/4h/1zb_7s1d4vd1xm5gv11pxsq80000gn/T/camlppxebab31' '/var/folders/4h/1zb_7s1d4vd1xm5gv11pxsq80000gn/T/camlppxbd5423' 1>/dev/null 2>/dev/null"
(merlin) backtrace: 
Merlin failed with error: "Error while running external preprocessor
Command line: ../_build/default/.ppx/ppx_sexp_conv+ppx_cstruct/ppx.exe --as-ppx --cookie 'library-name=dhcp_wire' -no-check '/var/folders/4h/1zb_7s1d4vd1xm5gv11pxsq80000gn/T/camlppxca8cc8' '/var/folders/4h/1zb_7s1d4vd1xm5gv11pxsq80000gn/T/camlppx9b2fd2' 1>/dev/null 2>/dev/null"

If I run by hand I get:

feanor:lib: ../_build/default/.ppx/ppx_sexp_conv+ppx_cstruct/ppx.exe --as-ppx --cookie 'library-name=dhcp_wire' -no-check '/var/folders/4h/1zb_7s1d4vd1xm5gv11pxs>
ppx.exe: unknown option '--cookie'.
ppx.exe [options] <input ast file> <output ast file>
  -loc-filename <string> File name to use in locations
  -reserve-namespace <string> Mark the given namespace as reserved
  -no-check  Disable checks (unsafe)
  -apply <names> Apply these transformations in order (comma-separated list)
  -dont-apply <names> Exclude these transformations
  -no-merge  Do not merge context free transformations (better for debugging rewriters)
  -help  Display this list of options
  --help  Display this list of options

It seems jbuilder is generating a bad FLG line, since --cookie is invalid, maybe this is an old option ?

**Comment by haesbaert** [comment]
Indeed it is the cookie line, if I remove just the cookie option, the problem is fixed:
--cookie 'library-name=dhcp_wire'

I've never used jbuilder so I'm at lost here, maybe @rgrinberg could shed some light ?

**Comment by rgrinberg** [comment]
First, make sure that you're using a recent version of merlin. Only recent versions of merlin support quoting in the FLG argument (https://github.com/janestreet/jbuilder/issues/30)

 If that doesn't do anything then I'd make a bug ticket in jbuilder itself:

```
FLG -ppx "../_build/default/.ppx/ppx_sexp_conv+ppx_cstruct/ppx.exe --as-ppx --cookie 'library-name="dhcp_wire"' -no-check"
```

I see that the inner double quotes in the FLG argument aren't being escaped properly. That seems suspicious to me.

But definitely make sure you have the most recent versions of merlin and jbuilder first.

**Comment by haesbaert** [comment]
Thanks, I think I have the latest:
merlin 2.5.5
jbuilder 1.0+beta10

I also tried jbuilder "current", same problem.

**Comment by haesbaert** [comment]
Even if the escaping is wrong the binary doesn't seem to have --cookie at all

**Comment by rgrinberg** [comment]
cookie is certainly an argument to some of the ppx.exe's jbuilder builds for me:
```
ppx.exe [options] [<files>]
  --as-ppx                    Act as a -ppx rewriter
  --as-pp                     Shorthand for: --dump-ast --embed-errors
  --dump-ast                  Output a binary AST instead of source code
  -o FILE                     Output to this file instead of the standard output
  --intf FILE                 Treat FILE as a .mli file
  --impl FILE                 Treat FILE as a .ml file
  --cookie NAME=EXPR          Set the cookie NAME to EXPR
  --embed-errors              Embed error reported by rewriters into the AST
  -loc-filename <string>      File name to use in locations
  -reserve-namespace <string> Mark the given namespace as reserved
  -no-check                   Disable checks (unsafe)
  -apply <names>              Apply these transformations in order (comma-separated list)
  -dont-apply <names>         Exclude these transformations
  -no-merge                   Do not merge context free transformations (better for debugging rewriters)
  -help                       Display this list of options
  --help                      Display this list of options
```

I can't build charrua-core at the moment unfortunately, otherwise I'd check here too.

**Comment by haesbaert** [comment]
Indeed it shows up in help, my bad, it's weird that --help prints something different than passing an invalid argument.

feanor:lib: ../_build/default/.ppx/ppx_sexp_conv+ppx_cstruct/ppx.exe --as-ppx -no-check --cookie "foo=bar" /var/folders/4h/1zb_7s1d4vd1xm5gv11pxsq80000gn/T/camlp>
ppx.exe: unknown option '--cookie'.

feanor:lib: ../_build/default/.ppx/ppx_sexp_conv+ppx_cstruct/ppx.exe --cookie 'foo=bar'
feanor:lib: echo $?
0

ok so the option is there, but if I pass ppx:
feanor:lib: ../_build/default/.ppx/ppx_sexp_conv+ppx_cstruct/ppx.exe --as-ppx --cookie 'foo=bar'
File "_none_", line 1:
Error: I/O error: --cookie: No such file or directory
feanor:lib: ../_build/default/.ppx/ppx_sexp_conv+ppx_cstruct/ppx.exe --as-ppx --cookie 'foo=bar' bla bla
ppx.exe: unknown option '--cookie'.
ppx.exe [options] <input ast file> <output ast file>

and ppx must be first, check this out:
feanor:lib: ../_build/default/.ppx/ppx_sexp_conv+ppx_cstruct/ppx.exe --as-ppx --cookie 'foo=bar'
File "_none_", line 1:
Error: I/O error: --cookie: No such file or directory
feanor:lib: ../_build/default/.ppx/ppx_sexp_conv+ppx_cstruct/ppx.exe --as-ppx --cookie 'foo=bar' bla bla
ppx.exe: unknown option '--cookie'.
ppx.exe [options] <input ast file> <output ast file>

**Comment by rgrinberg** [comment]
Hmm, what if you move `-no-check` to be the first argument to ppx.exe? To me right now it seems like an issue with `-no-check`. Which you can  also remove by editing charrua's jbuild files.

**Comment by haesbaert** [comment]
Hmm no luck, --as-ppx must be the first:

feanor:lib: ../_build/default/.ppx/ppx_sexp_conv+ppx_cstruct/ppx.exe -no-check --as-ppx --cookie "foo=bar" /var/folders/4h/1zb_7s1d4vd1xm5gv11pxsq80000gn/T/camlp>
../_build/default/.ppx/ppx_sexp_conv+ppx_cstruct/ppx.exe: --as-ppx must be passed as first argument.

**Comment by rgrinberg** [comment]
And without `-no-check` at all? AFAIK, removing should only add warnings.

I think we'll need to ask @let-def if the argument order passed to omp is correct here.

**Comment by haesbaert** [comment]
If I remove I get back to unknown --cookie option :/

**Comment by haesbaert** [comment]
Problem appears to be fixed.
